update_readme:
  stage: build
  script:
    - curl -X POST -F token=$README_TOKEN -F ref=master -F variables[single_repo]=weatheralerts https://gitlab.com/api/v4/projects/7064305/trigger/pipeline
push_github:
  stage: deploy
  script:
    - curl -sL https://gitlab.com/ludeeus/toolbox/raw/master/CI-Scripts/push_to_public_repo/init.sh | bash -s github HA-Custom_components root /weatheralerts
    - curl -sL https://gitlab.com/ludeeus/toolbox/raw/master/CI-Scripts/push_to_public_repo/push.sh | bash -s Europe/Oslo
